# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Template-Alloy-XS
version:      1.003
version_from: lib/Template/Alloy/XS.pm
installdirs:  site
requires:
    Template::Alloy:               1.002

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
