--- #YAML:1.0
name:               Template-Alloy-XS
version:            1.004
abstract:           XS version of key parts of Template::Alloy
author:
    - Paul Seamons <perl@seamons.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Template::Alloy:  1.002
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
